services:
  proxy:
    image: traefik:v2.11
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  client:
    build:
      context: ./../
      target: client-dev
    develop:
      watch:
        - path: ./src
          action: sync
          target: /src/app

        - path: ./package.json
          action: rebuild

    ports:
      - 5173:5173

    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 5174
